const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),overlay=document.querySelector('#overlay'),message=document.querySelector('#message'),startButton=document.querySelector('#start'),statusEl=document.querySelector('#status');
const COLS=20,CELL=canvas.width/COLS,directions={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},opposites={up:'down',down:'up',left:'right',right:'left'};
let snake,food,direction,queued,score,timer,running=false,paused=false,best=Number(localStorage.getItem('serpent-best')||0);bestEl.textContent=String(best).padStart(4,'0');
function reset(){snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10},{x:7,y:10}];direction='right';queued='right';score=0;scoreEl.textContent='0000';placeFood();draw()}
function placeFood(){const spaces=[];for(let y=0;y<COLS;y++)for(let x=0;x<COLS;x++)if(!snake?.some(p=>p.x===x&&p.y===y))spaces.push({x,y});food=spaces[Math.floor(Math.random()*spaces.length)]}
function setDirection(next){if(!directions[next]||opposites[direction]===next)return;queued=next;const key=document.querySelector(`[data-direction="${next}"]`);key?.classList.add('active');setTimeout(()=>key?.classList.remove('active'),100)}
function tick(){if(!running||paused)return;direction=queued;const d=directions[direction],head={x:snake[0].x+d.x,y:snake[0].y+d.y},hitWall=head.x<0||head.y<0||head.x>=COLS||head.y>=COLS,hitSelf=snake.some((p,i)=>i<snake.length-1&&p.x===head.x&&p.y===head.y);if(hitWall||hitSelf){endGame();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;scoreEl.textContent=String(score).padStart(4,'0');placeFood();restartTimer()}else snake.pop();draw()}
function restartTimer(){clearInterval(timer);timer=setInterval(tick,Math.max(62,132-Math.floor(score/50)*8))}
function startGame(){reset();running=true;paused=false;overlay.classList.add('hidden');statusEl.textContent='RUN';restartTimer()}
function endGame(){running=false;clearInterval(timer);best=Math.max(best,score);localStorage.setItem('serpent-best',best);bestEl.textContent=String(best).padStart(4,'0');statusEl.textContent='OVER';message.textContent='GAME OVER';startButton.textContent='PLAY AGAIN';overlay.classList.remove('hidden')}
function togglePause(){if(!running)return;paused=!paused;statusEl.textContent=paused?'PAUSED':'RUN';message.textContent='PAUSED';startButton.textContent='RESUME';overlay.classList.toggle('hidden',!paused)}
function draw(){ctx.fillStyle='#b9c889';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='rgba(29,44,29,.055)';ctx.lineWidth=1;for(let i=0;i<=COLS;i++){ctx.beginPath();ctx.moveTo(i*CELL,0);ctx.lineTo(i*CELL,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*CELL);ctx.lineTo(canvas.width,i*CELL);ctx.stroke()}ctx.fillStyle='#263a22';ctx.fillRect(food.x*CELL+4,food.y*CELL+4,CELL-8,CELL-8);ctx.fillRect(food.x*CELL+7,food.y*CELL+1,4,4);snake.forEach((p,i)=>{ctx.fillStyle=i===0?'#142418':'#294029';ctx.fillRect(p.x*CELL+1,p.y*CELL+1,CELL-2,CELL-2);if(i===0){ctx.fillStyle='#b9c889';const ex=direction==='left'?4:direction==='right'?12:5;ctx.fillRect(p.x*CELL+ex,p.y*CELL+5,3,3);ctx.fillRect(p.x*CELL+ex,p.y*CELL+11,3,3)}})}
document.addEventListener('keydown',e=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};if(map[e.key]){e.preventDefault();setDirection(map[e.key]);if(!running)startGame()}if(e.code==='Space'){e.preventDefault();togglePause()}});
document.querySelectorAll('[data-direction]').forEach(btn=>btn.addEventListener('pointerdown',e=>{e.preventDefault();setDirection(btn.dataset.direction);if(!running)startGame()}));startButton.addEventListener('click',()=>paused?togglePause():startGame());reset();
